replicaCount: 2

image:
  repository: kiran9871/flask-app
  pullPolicy: IfNotPresent
  tag: 49f3044387fbdbcd248745e77d4bd8415f356005

service:
  type: NodePort
  port: 5000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

resources: {}