replicaCount: 2

image:
  repository: kiran9871/flask-app
  pullPolicy: IfNotPresent
  tag: "b88a890c26eba75a514e58dd110da3b661496101"

service:
  type: NodePort
  port: 5000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /health
    port: http

readinessProbe:
  httpGet:
    path: /health
    port: http

resources: {}