replicaCount: 2

image:
  repository: flask-app
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: NodePort
  port: 5000

serviceAccount:
  create: false

ingress:
  enabled: false

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

resources: {}